networks:
  backend:
    driver: bridge

services:
    nginx:
        restart: always
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/var/django/backend/static
        networks:
            - backend
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /var/django/docker/backend/server.sh
        volumes:
            - static_volume:/var/django/backend/static
        expose:
            - 8000
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379"
            CELERY_RESULT_BACKEND: "redis://redis:6379"
            DJANGO_DB: 'mysql'
            MYSQL_HOST: 'dbase'
            MYSQL_DATABASE: 'library'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'topsecret'
            MYSQL_ROOT_PASSWORD: 'R00tP@ss'
            MYSQL_PORT: 3306
        networks:
            - backend
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /var/django/docker/backend/worker.sh
        volumes:
            - static_volume:/var/django/backend/static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379"
            CELERY_RESULT_BACKEND: "redis://redis:6379"
            DJANGO_DB: 'mysql'
            MYSQL_HOST: 'dbase'
            MYSQL_DATABASE: 'library'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'topsecret'
            MYSQL_ROOT_PASSWORD: 'R00tP@ss'
            MYSQL_PORT: 3306
        depends_on:
            - server
            - redis
        networks:
            - backend
    redis:
        restart: unless-stopped
        image: redis:7-alpine
        expose:
            - 6379
        networks:
            - backend
    dbase:
        image: mysql:latest
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'library'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'topsecret'
            MYSQL_ROOT_PASSWORD: 'R00tP@ss'
        expose:
            - 3306
        networks:
            - backend
volumes:
    static_volume: {}
    mysql_data: {}
